### ISSUE TITLE
Is there a way to make the status colors vibrant as discords original?

### ISSUE THREAD

**Issue by BrianTheBrain11** [Daggy1234/Nord#2]
[
![image_2021-03-17_115858](https://user-images.githubusercontent.com/68790720/111523138-284c8380-8718-11eb-84de-5a3a69fc6e40.png)
](url)

As you can see in this pic, the status colors look much more muted than the original. Is there anyway to make it so that they stay their original color?

**Comment by daggy1234** [comment]
Oh that was deliberate, the colors I felt were very harsh. You can comment out that part.

https://github.com/DagCord/Nord/blob/master/nord.css#L108-L125

**Comment by BrianTheBrain11** [comment]
Okay great! Thanks!
